### ISSUE TITLE
Deleting Energy efficiency upgrade crashes server/world.

### ISSUE THREAD

**Issue by plazia** [Poenjabiesous/OpenModularTurrets#45]
Deleting Energy efficiency upgrade crashes server/world.

Was messing about in survival but had the ability to cheat in items.
I made a resonant turret base and put in the energy efficiency upgrade.
When removing it and transferring it to the NEI items window on the right (to delete the item), the server crashed back to the ATLauncher.

I tried to load back in and it simply wouldn't even load the world.

Other than this - absolutely LOVE this mod.

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 1/27/15 12:01 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at openmodularturrets.tileentity.turrets.TurretHeadUtils.getRangeUpgrades(TurretHeadUtils.java:214)
	at openmodularturrets.tileentity.turrets.TurretHead.getTarget(TurretHead.java:109)
	at openmodularturrets.tileentity.turrets.TurretHead.func_145845_h(TurretHead.java:215)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Keridos** [comment]
Will be fixed in next version, found the issue already.
